defmodule AshTemplateWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ash_template

  # A connected mount reads the cookie the socket handshake carried, so the
  # transport must decode it with the same options the request plug runs with.
  @session_options {Application, :fetch_env!, [:ash_template, :session_options]}

  # A stylesheet, an icon or an image may be opened directly, and the browser
  # then reads it as a page. These say what a page from this address may do,
  # which is nothing.
  @static_headers %{
    "content-security-policy" => "default-src 'none'; frame-ancestors 'none'",
    "x-content-type-options" => "nosniff",
    "x-frame-options" => "DENY",
    "referrer-policy" => "no-referrer"
  }

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :uri, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :uri, session: @session_options]]

  plug AshTemplateWeb.Plugs.CanonicalHost
  plug AshTemplateWeb.Plugs.ContractHeaders

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ash_template,
    gzip: not code_reloading?,
    only: AshTemplateWeb.static_paths(),
    only_matching: AshTemplateWeb.digested_static_prefixes(),
    raise_on_missing_only: code_reloading?,
    headers: @static_headers

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Every answer, including the Markdown and refusals the next plug gives
  # before the router, lets browser agents use the tools this site's pages
  # register, and no other site's.
  plug :allow_page_tools

  # One budget per client address, shared by the health check and every /api
  # path, answered or not. Every answer says what is left of it; past it the
  # answer is 429 with Retry-After.
  plug :limit_rate

  # Before the parsers, so a body they reject on an /api path is answered in
  # JSON like every other API error.
  plug RegentAgentAccess.Plug,
    documents: &AshTemplateWeb.PublicDocuments.document/1,
    guide: "/llms.txt"

  plug AshTemplateWeb.Plugs.Parsers,
    body_reader: {RegentIdentity.BodyReader, :read_body, []},
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug AshTemplateWeb.Plugs.RuntimeSession
  plug AshTemplateWeb.Router

  @rate_limit RegentAgentAccess.RateLimit.init(
                policy: "default",
                limit: 120,
                window: 60,
                admit: &AshTemplate.Accounts.RequestRateLimiter.admit/3,
                key: &AshTemplateWeb.ClientAddress.key/1
              )

  defp limit_rate(%Plug.Conn{path_info: ["healthz"]} = conn, _opts),
    do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  defp limit_rate(%Plug.Conn{path_info: ["api" | _]} = conn, _opts),
    do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  defp limit_rate(conn, _opts), do: conn

  defp allow_page_tools(conn, _opts),
    do: Plug.Conn.put_resp_header(conn, "permissions-policy", "tools=(self)")
end
