defmodule AshTemplate.Repo.Migrations.AddNoteDecisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:note_decisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:question, :text, null: false)
      add(:choices, {:array, :text}, null: false)
      add(:state, :text, null: false, default: "pending")
      add(:choice, :text)
      add(:confidence, :float)
      add(:model, :text)
      add(:input_tokens, :bigint)
      add(:output_tokens, :bigint)
      add(:cost_usd, :decimal)
      add(:failure, :text)
      add(:report, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :note_id,
        references(:notes,
          column: :id,
          name: "note_decisions_note_id_fkey",
          type: :uuid,
          prefix: "ash_template_app",
          on_delete: :delete_all
        ), null: false)

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "note_decisions_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)
    end

    create index(:note_decisions, [:inserted_at])

    create index(:note_decisions, [:note_id, :inserted_at])
  end

  def down do
    drop_if_exists(index(:note_decisions, [:note_id, :inserted_at]))

    drop_if_exists(index(:note_decisions, [:inserted_at]))

    drop(constraint(:note_decisions, "note_decisions_human_account_id_fkey"))

    drop(constraint(:note_decisions, "note_decisions_note_id_fkey"))

    drop(table(:note_decisions))
  end
end
