defmodule AshTemplate.Repo.Migrations.AgentNoteEpisode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notes) do
      add(:created_by_pairing_id, :uuid)
    end
  end

  def down do
    alter table(:notes) do
      remove(:created_by_pairing_id)
    end
  end
end
