defmodule AshTemplate.Repo.Migrations.AddNoteWebhook do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notes) do
      add(:revision, :bigint, null: false, default: 1)
      add(:webhook_state, :text)
    end
  end

  def down do
    alter table(:notes) do
      remove(:webhook_state)
      remove(:revision)
    end
  end
end
