defmodule AshTemplate.Repo.Migrations.AddNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:body, :text)
      add(:path, :text, null: false)
      add(:read_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "notifications_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)
    end

    create index(:notifications, [:human_account_id, :inserted_at])
  end

  def down do
    drop_if_exists(index(:notifications, [:human_account_id, :inserted_at]))

    drop(constraint(:notifications, "notifications_human_account_id_fkey"))

    drop(table(:notifications))
  end
end
