defmodule AshTemplate.Repo.Migrations.AddAgentWorldId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agents) do
      add(:world_id_human_id, :text)
      add(:world_id_agent_count, :bigint)
    end

    create constraint(:agents, :world_id_whole,
             check: """
               (world_id_human_id IS NULL) = (world_id_agent_count IS NULL)
             """
           )
  end

  def down do
    drop_if_exists(constraint(:agents, :world_id_whole))

    alter table(:agents) do
      remove(:world_id_agent_count)
      remove(:world_id_human_id)
    end
  end
end
