defmodule AshTemplate.Repo.Migrations.AgentMarks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notes) do
      add(
        :changed_by_agent_id,
        references(:agents,
          column: :id,
          name: "notes_changed_by_agent_id_fkey",
          type: :uuid,
          prefix: "ash_template_app"
        )
      )
    end

    alter table(:room_messages) do
      add(
        :via_agent_id,
        references(:agents,
          column: :id,
          name: "room_messages_via_agent_id_fkey",
          type: :uuid,
          prefix: "ash_template_app"
        )
      )
    end
  end

  def down do
    drop(constraint(:room_messages, "room_messages_via_agent_id_fkey"))

    alter table(:room_messages) do
      remove(:via_agent_id)
    end

    drop(constraint(:notes, "notes_changed_by_agent_id_fkey"))

    alter table(:notes) do
      remove(:changed_by_agent_id)
    end
  end
end
