defmodule AshTemplate.Repo.Migrations.AddAiChat do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_conversations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:title, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "chat_conversations_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)
    end

    create index(:chat_conversations, [:human_account_id])

    create table(:chat_messages, primary_key: false) do
      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:text, :text, null: false)
      add(:tool_calls, {:array, :map})
      add(:tool_results, {:array, :map})
      add(:source, :text, null: false, default: "user")
      add(:complete, :boolean, null: false, default: true)

      add(
        :conversation_id,
        references(:chat_conversations,
          column: :id,
          name: "chat_messages_conversation_id_fkey",
          type: :uuid,
          prefix: "ash_template_app"
        ), null: false)

      add(
        :response_to_id,
        references(:chat_messages,
          column: :id,
          name: "chat_messages_response_to_id_fkey",
          type: :uuid,
          prefix: "ash_template_app"
        )
      )
    end

    create index(:chat_messages, [:conversation_id, :inserted_at])
  end

  def down do
    drop_if_exists(index(:chat_messages, [:conversation_id, :inserted_at]))

    drop(constraint(:chat_messages, "chat_messages_response_to_id_fkey"))

    drop(constraint(:chat_messages, "chat_messages_conversation_id_fkey"))

    drop(table(:chat_messages))

    drop_if_exists(index(:chat_conversations, [:human_account_id]))

    drop(constraint(:chat_conversations, "chat_conversations_human_account_id_fkey"))

    drop(table(:chat_conversations))
  end
end
