defmodule AshTemplate.Repo.Migrations.PairedAgentAttribution do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:note_decisions) do
      add(:pairing_id, :uuid)
    end

    alter table(:notes) do
      add(:changed_by_pairing_id, :uuid)
    end
  end

  def down do
    alter table(:notes) do
      remove(:changed_by_pairing_id)
    end

    alter table(:note_decisions) do
      remove(:pairing_id)
    end
  end
end
