defmodule AshTemplate.Repo.Migrations.AddRooms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:room_messages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:room, :text, null: false)
      add(:body, :text, null: false)
      add(:author_name, :text, null: false)
      add(:edited_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "room_messages_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)
    end

    create index(:room_messages, [:room, :inserted_at])

    create table(:room_mutes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:muted_name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :muter_account_id,
        references(:platform_human_users,
          column: :id,
          name: "room_mutes_muter_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)

      add(
        :muted_account_id,
        references(:platform_human_users,
          column: :id,
          name: "room_mutes_muted_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)
    end

    create unique_index(:room_mutes, [:muter_account_id, :muted_account_id],
             name: "room_mutes_one_per_pair_index"
           )
  end

  def down do
    drop(constraint(:room_mutes, "room_mutes_muted_account_id_fkey"))

    drop(constraint(:room_mutes, "room_mutes_muter_account_id_fkey"))

    drop_if_exists(
      unique_index(:room_mutes, [:muter_account_id, :muted_account_id],
        name: "room_mutes_one_per_pair_index"
      )
    )

    drop(table(:room_mutes))

    drop_if_exists(index(:room_messages, [:room, :inserted_at]))

    drop(constraint(:room_messages, "room_messages_human_account_id_fkey"))

    drop(table(:room_messages))
  end
end
