defmodule AshTemplate.Repo.Migrations.AddAgents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:wallet_address, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:agents, [:wallet_address], name: "agents_unique_wallet_address_index")

    alter table(:room_messages) do
      add(
        :agent_id,
        references(:agents,
          column: :id,
          name: "room_messages_agent_id_fkey",
          type: :uuid,
          prefix: "ash_template_app"
        )
      )

      modify(:human_account_id, :bigint, null: true)
    end

    create constraint(:room_messages, :one_author,
             check: """
               (human_account_id IS NULL) <> (agent_id IS NULL)
             """
           )

    drop_if_exists(
      unique_index(:room_mutes, [:muter_account_id, :muted_account_id],
        name: "room_mutes_one_per_pair_index"
      )
    )

    alter table(:room_mutes) do
      add(
        :muted_agent_id,
        references(:agents,
          column: :id,
          name: "room_mutes_muted_agent_id_fkey",
          type: :uuid,
          prefix: "ash_template_app"
        )
      )
    end

    create unique_index(:room_mutes, [:muter_account_id, :muted_account_id, :muted_agent_id],
             name: "room_mutes_one_per_pair_index",
             nulls_distinct: false
           )

    alter table(:room_mutes) do
      modify(:muted_account_id, :bigint, null: true)
    end

    create constraint(:room_mutes, :one_muted_author,
             check: """
               (muted_account_id IS NULL) <> (muted_agent_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists(constraint(:room_mutes, :one_muted_author))

    drop(constraint(:room_mutes, "room_mutes_muted_agent_id_fkey"))

    alter table(:room_mutes) do
      modify(:muted_account_id, :bigint, null: false)
    end

    drop_if_exists(
      unique_index(:room_mutes, [:muter_account_id, :muted_account_id, :muted_agent_id],
        name: "room_mutes_one_per_pair_index"
      )
    )

    alter table(:room_mutes) do
      remove(:muted_agent_id)
    end

    create unique_index(:room_mutes, [:muter_account_id, :muted_account_id],
             name: "room_mutes_one_per_pair_index"
           )

    drop_if_exists(constraint(:room_messages, :one_author))

    drop(constraint(:room_messages, "room_messages_agent_id_fkey"))

    alter table(:room_messages) do
      modify(:human_account_id, :bigint, null: false)
      remove(:agent_id)
    end

    drop_if_exists(
      unique_index(:agents, [:wallet_address], name: "agents_unique_wallet_address_index")
    )

    drop(table(:agents))
  end
end
