defmodule AshTemplate.Repo.Migrations.InitialApp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:linked_identities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:subject, :text, null: false)
      add(:username, :text)
      add(:display_name, :text)
      add(:verified_at, :utc_datetime_usec, null: false)
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "linked_identities_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ), null: false)
    end

    create unique_index(:linked_identities, [:provider, :human_account_id],
             name: "linked_identities_unique_provider_per_account_index"
           )

    create unique_index(:linked_identities, [:provider, :subject],
             name: "linked_identities_unique_subject_per_provider_index"
           )

    create table(:session_authorities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:lineage_digest, :binary, null: false)
      add(:generation, :bigint, null: false, default: 0)
      add(:revoked_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "session_authorities_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names",
          on_delete: :restrict
        )
      )
    end

    create unique_index(:session_authorities, [:lineage_digest],
             name: "session_authorities_unique_lineage_digest_index"
           )

    create constraint(:session_authorities, :session_authorities_generation_nonnegative,
             check: """
               generation >= 0
             """
           )
  end

  def down do
    drop_if_exists(constraint(:session_authorities, :session_authorities_generation_nonnegative))

    drop(constraint(:session_authorities, "session_authorities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:session_authorities, [:lineage_digest],
        name: "session_authorities_unique_lineage_digest_index"
      )
    )

    drop(table(:session_authorities))

    drop(constraint(:linked_identities, "linked_identities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:linked_identities, [:provider, :subject],
        name: "linked_identities_unique_subject_per_provider_index"
      )
    )

    drop_if_exists(
      unique_index(:linked_identities, [:provider, :human_account_id],
        name: "linked_identities_unique_provider_per_account_index"
      )
    )

    drop(table(:linked_identities))
  end
end
